import { PrismaClient } from '@prisma/client';
import { OutlookService } from './outlook.service';
import { TaskService } from './task.service';
import { DraftService } from './draft.service';
import { MeetingService } from './meeting.service';

const prisma = new PrismaClient();

export class AgentService {
  async runAutomatedProcessing(userId: string): Promise<{
    emailsProcessed: number;
    tasksCreated: number;
    draftsGenerated: number;
    meetingsExtracted: number;
  }> {
    try {
      // Get user and agent settings
      const user = await ((prisma as any).user.findUnique({
        where: { id: userId },
        include: { agentSettings: true }
      }) as any);

      if (!user) {
        throw new Error('User not found');
      }

      // Get or create agent settings
      let settings = user.agentSettings;
      if (!settings) {
        settings = await ((prisma as any).agentSettings.create({
          data: { userId } as any
        }) as any);
      }

      if (!settings.enabled) {
        console.log(`Agent disabled for user ${userId}`);
        return { emailsProcessed: 0, tasksCreated: 0, draftsGenerated: 0, meetingsExtracted: 0 };
      }

      const outlookService = new OutlookService(user.accessToken);

      // Fetch new emails from Outlook
      const emails = await outlookService.fetchEmails(20);

      let emailsProcessed = 0;
      let tasksCreated = 0;
      let draftsGenerated = 0;
      let meetingsExtracted = 0;

      for (const email of emails) {
        // Check if email already processed
        const existing = await (prisma.email.findUnique({
          where: { outlookId: email.id } as any
        }) as any);

        if (existing?.processed) {
          continue;
        }

        // Store email
        const dbEmail = await (prisma.email.upsert({
          where: { outlookId: email.id } as any,
          update: {},
          create: {
            userId,
            outlookId: email.id,
            subject: email.subject,
            from: email.from,
            body: email.body,
            receivedAt: email.receivedAt,
            processed: false
          } as any
        }) as any);

        // Log email processing activity
        await this.logActivity(
          userId,
          'EMAIL_PROCESSED',
          `Processed email: ${email.subject}`,
          `From: ${email.from}`,
          dbEmail.id
        );

        emailsProcessed++;

        // Extract tasks if enabled
        if (settings.autoProcessEmails) {
          const taskService = new TaskService();
          const result = await taskService.processEmail(userId, email, outlookService);
          tasksCreated += result.tasksCreated;

          // Log task creation
          if (result.tasksCreated > 0) {
            await this.logActivity(
              userId,
              'TASK_CREATED',
              `Created ${result.tasksCreated} task(s) from email`,
              `Email: ${email.subject}`,
              dbEmail.id
            );
          }
        }

        // Extract meetings if enabled
        if (settings.autoExtractMeetings) {
          const meetingService = new MeetingService();
          const extractedMeetings = await meetingService.extractMeetingsFromEmail(
            email.subject,
            email.body,
            email.from
          );

          for (const meeting of extractedMeetings) {
            const savedMeeting = await meetingService.saveMeeting(userId, dbEmail.id, meeting);
            meetingsExtracted++;

            await this.logActivity(
              userId,
              'MEETING_EXTRACTED',
              `Extracted meeting: ${meeting.title}`,
              `Start: ${meeting.startTime}`,
              dbEmail.id,
              undefined,
              undefined,
              savedMeeting.id
            );
          }
        }

        // Generate drafts for high priority emails if enabled
        if (settings.autoGenerateDrafts) {
          const highPriorityTasks = await prisma.task.findMany({
            where: { emailId: dbEmail.id, priority: 'HIGH' },
            take: 1
          });

          if (highPriorityTasks.length > 0) {
            const draftService = new DraftService();
            const draft = await draftService.generateDraftResponse(
              email.subject,
              email.body,
              email.from,
              `High priority task: ${highPriorityTasks[0].title}`
            );

            const savedDraft = await draftService.saveDraft(
              userId,
              dbEmail.id,
              highPriorityTasks[0].id,
              draft
            );

            draftsGenerated++;

            await this.logActivity(
              userId,
              'DRAFT_GENERATED',
              `Generated draft reply for high priority email`,
              `Subject: ${draft.subject}`,
              dbEmail.id,
              highPriorityTasks[0].id,
              savedDraft.id
            );
          }
        }
      }

      return {
        emailsProcessed,
        tasksCreated,
        draftsGenerated,
        meetingsExtracted
      };
    } catch (error) {
      console.error('Error in automated processing:', error);
      throw error;
    }
  }

  async logActivity(
    userId: string,
    activityType: 'EMAIL_PROCESSED' | 'TASK_CREATED' | 'DRAFT_GENERATED' | 'MEETING_EXTRACTED' | 'EMAIL_SENT',
    action: string,
    details?: string,
    emailId?: string,
    taskId?: string,
    draftId?: string,
    meetingId?: string
  ) {
    return await (prisma.agentActivity.create({
      data: {
        userId,
        activityType,
        action,
        details,
        emailId,
        taskId,
        draftId,
        meetingId,
        status: 'AUTO_APPROVED' // For now, auto-approve all activities
      } as any
    }) as any);
  }

  async getActivities(userId: string, limit: number = 50) {
    return await (prisma.agentActivity.findMany({
      where: { userId } as any,
      orderBy: { createdAt: 'desc' },
      take: limit
    }) as any);
  }

  async getSettings(userId: string) {
    let settings = await ((prisma as any).agentSettings.findUnique({
      where: { userId } as any
    }) as any);

    if (!settings) {
      settings = await ((prisma as any).agentSettings.create({
        data: { userId } as any
      }) as any);
    }

    return settings;
  }

  async updateSettings(userId: string, updates: {
    enabled?: boolean;
    checkIntervalMinutes?: number;
    autoProcessEmails?: boolean;
    autoGenerateDrafts?: boolean;
    autoExtractMeetings?: boolean;
    requireApprovalForSend?: boolean;
  }) {
    return await ((prisma as any).agentSettings.upsert({
      where: { userId } as any,
      update: updates,
      create: {
        userId,
        ...updates
      } as any
    }) as any);
  }

  async getActivityStats(userId: string) {
    const activities = await (prisma.agentActivity.findMany({
      where: { userId } as any,
      orderBy: { createdAt: 'desc' }
    }) as any);

    const last24Hours = new Date(Date.now() - 24 * 60 * 60 * 1000);
    const recentActivities = activities.filter(a => new Date(a.createdAt) > last24Hours);

    return {
      total: activities.length,
      last24Hours: recentActivities.length,
      byType: {
        emailsProcessed: activities.filter(a => a.activityType === 'EMAIL_PROCESSED').length,
        tasksCreated: activities.filter(a => a.activityType === 'TASK_CREATED').length,
        draftsGenerated: activities.filter(a => a.activityType === 'DRAFT_GENERATED').length,
        meetingsExtracted: activities.filter(a => a.activityType === 'MEETING_EXTRACTED').length,
        emailsSent: activities.filter(a => a.activityType === 'EMAIL_SENT').length
      }
    };
  }

  async clearActivities(userId: string) {
    return await (prisma.agentActivity.deleteMany({
      where: { userId } as any
    }) as any);
  }

  async getComprehensiveSummary(userId: string) {
    const [
      settings,
      activities,
      stats,
      pendingDrafts,
      upcomingMeetings,
      tasks
    ] = await Promise.all([
      this.getSettings(userId),
      this.getActivities(userId, 100),
      this.getActivityStats(userId),
      (prisma.draft.count({ where: { userId, status: 'PENDING' } as any }) as any),
      (prisma.meeting.count({
        where: {
          userId,
          startTime: { gte: new Date() }
        } as any
      }) as any),
      (prisma.task.findMany({
        where: { userId } as any,
        select: { status: true, priority: true }
      }) as any)
    ]);

    const last7Days = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
    const recentActivities = activities.filter(a => new Date(a.createdAt) > last7Days);

    // Calculate task breakdown
    const taskStats = {
      total: tasks.length,
      pending: tasks.filter(t => t.status === 'PENDING').length,
      inProgress: tasks.filter(t => t.status === 'IN_PROGRESS').length,
      completed: tasks.filter(t => t.status === 'COMPLETED').length,
      highPriority: tasks.filter(t => t.priority === 'HIGH' && t.status !== 'COMPLETED').length
    };

    return {
      settings,
      stats,
      pendingDrafts,
      upcomingMeetings,
      taskStats,
      recentActivities: {
        count: recentActivities.length,
        last7Days: recentActivities
      },
      lastActivity: activities[0] || null,
      isActive: settings.enabled
    };
  }
}
