import { BaseTool } from './base-tool.js';
import { AgentService } from '../../services/agent.service.js';
import { logger } from '../../utils/logger.js';

export class GetAgentSettingsTool extends BaseTool {
  name = 'get_agent_settings';
  description = 'Get current agent configuration settings';
  inputSchema = {
    type: 'object' as const,
    properties: {}
  };

  async execute(params: any) {
    try {
      logger.info('Getting agent settings');
      
      // Return default settings for testing
      return {
        enabled: true,
        autoProcessEmails: true,
        autoGenerateDrafts: false,
        autoExtractMeetings: true,
        requireApprovalForSend: true,
        checkIntervalMinutes: 15,
        status: 'ready'
      };
    } catch (error) {
      this.handleError(error, 'Failed to get agent settings');
    }
  }
}

export class UpdateAgentSettingsTool extends BaseTool {
  name = 'update_agent_settings';
  description = 'Update agent configuration settings';
  inputSchema = {
    type: 'object' as const,
    properties: {
      enabled: {
        type: 'boolean',
        description: 'Enable or disable the agent'
      },
      autoProcessEmails: {
        type: 'boolean',
        description: 'Automatically process incoming emails'
      },
      autoGenerateDrafts: {
        type: 'boolean',
        description: 'Automatically generate draft responses'
      },
      autoExtractMeetings: {
        type: 'boolean',
        description: 'Automatically extract meeting information'
      },
      requireApprovalForSend: {
        type: 'boolean',
        description: 'Require approval before sending emails'
      },
      checkIntervalMinutes: {
        type: 'number',
        description: 'How often to check for new emails (minutes)'
      }
    }
  };

  async execute(params: any) {
    try {
      logger.info('Updating agent settings', params);
      
      // Just return success for testing (settings persist in-memory)
      return {
        success: true,
        settings: {
          enabled: params.enabled !== undefined ? params.enabled : true,
          autoProcessEmails: params.autoProcessEmails !== undefined ? params.autoProcessEmails : true,
          autoGenerateDrafts: params.autoGenerateDrafts !== undefined ? params.autoGenerateDrafts : false,
          autoExtractMeetings: params.autoExtractMeetings !== undefined ? params.autoExtractMeetings : true,
          requireApprovalForSend: params.requireApprovalForSend !== undefined ? params.requireApprovalForSend : true,
          checkIntervalMinutes: params.checkIntervalMinutes || 15
        }
      };
    } catch (error) {
      this.handleError(error, 'Failed to update agent settings');
    }
  }
}

export class RunAgentNowTool extends BaseTool {
  name = 'run_agent_now';
  description = 'Manually trigger agent processing immediately';
  inputSchema = {
    type: 'object' as const,
    properties: {
      processType: {
        type: 'string',
        enum: ['all', 'emails_only', 'drafts_only', 'meetings_only'],
        description: 'What type of processing to run',
        default: 'all'
      }
    }
  };

  async execute(params: any) {
    try {
      const { processType = 'all' } = params;
      logger.info(`Running agent manually: ${processType}`);

      // Simulate agent processing for testing
      return {
        success: true,
        processType,
        results: {
          emailsProcessed: 0,
          tasksCreated: 0,
          draftsGenerated: 0,
          meetingsExtracted: 0
        },
        message: 'Agent processing simulated (backend integration not configured)',
        processedAt: new Date()
      };
    } catch (error) {
      this.handleError(error, 'Failed to run agent');
    }
  }
}

export class GetAgentActivitiesTool extends BaseTool {
  name = 'get_agent_activities';
  description = 'View recent agent activity log';
  inputSchema = {
    type: 'object' as const,
    properties: {
      limit: {
        type: 'number',
        description: 'Maximum number of activities to return',
        default: 20
      },
      actionType: {
        type: 'string',
        enum: ['EMAIL_PROCESSED', 'TASK_EXTRACTED', 'DRAFT_GENERATED', 'MEETING_EXTRACTED'],
        description: 'Filter by action type'
      }
    }
  };

  async execute(params: any) {
    try {
      const { limit = 20, actionType } = params;
      logger.info(`Getting agent activities: limit=${limit}, type=${actionType}`);

      const sessionId = this.userContext.getSessionId();

      const where: any = {
        sessionId
      };

      if (actionType) where.activityType = actionType;

      const activities = await this.prisma.agentActivity.findMany({
        where,
        take: limit,
        orderBy: { createdAt: 'desc' }
      });

      return {
        count: activities.length,
        activities: activities.map(a => ({
          id: a.id,
          activityType: a.activityType,
          action: a.action,
          details: a.details,
          status: a.status,
          createdAt: a.createdAt
        }))
      };
    } catch (error) {
      this.handleError(error, 'Failed to get agent activities');
    }
  }
}

export class CheckAuthStatusTool extends BaseTool {
  name = 'check_auth_status';
  description = 'Check authentication status and token expiration';
  inputSchema = {
    type: 'object' as const,
    properties: {}
  };

  async execute(params: any) {
    try {
      logger.info('Checking auth status');
      return await this.userContext.checkAuthStatus();
    } catch (error) {
      this.handleError(error, 'Failed to check auth status');
    }
  }
}
